### PR TITLE
TypeScript Migration

### PR DESCRIPTION
**Pull request by scinscinscin**
This migrates the API to typescript and uses the yarn package manager instead of NPM.

The logic of the code has not been touched and has been tested to still work.

### CODE REVIEW

**Review by WarenGonzaga — APPROVED** [review]
All good

**Comment by WarenGonzaga** [comment]
I made a legacy branch of current dev branch so we can still go back if something goes wrong with this huge update.

**Comment by scinscinscin** [comment]
Thanks!

For everyone who wants to develop on typescript, you can recompile your changes on the fly using ``yarn watch`` 
and still use ``yarn dev`` for nodemon to watch new changes to the compiled javascript.

**Comment by WarenGonzaga** [comment]
> Thanks!
> 
> For everyone who wants to develop on typescript, you can recompile your changes on the fly using `yarn watch`
> and still use `yarn dev` for nodemon to watch new changes to the compiled javascript.

I'll update the documentation for that once merge nato sa main branch.

**Pull request merged**
